name: Build docker image

on:
  push:
    branches:
    - master

    tags:
    - '*'

env:
  BASE_IMAGE_STABILITY_TAG: 2.19.6
  NGINX131: '1.31.1'
  NGINX130: '1.30.2'

jobs:
  nginx131-build:
    strategy:
      matrix:
        arch:
          - amd64
          - arm64
        include:
          - arch: amd64
            runner: ubuntu-24.04
          - arch: arm64
            runner: ubuntu-24.04-arm
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v6
      - uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: build and push
        env:
          NGINX_VER: ${{ env.NGINX131 }}
          ARCH: ${{ matrix.arch }}
        run: |
          make
          make test
          make push
  nginx131-push:
    runs-on: ubuntu-latest
    needs:
      - nginx131-build
    steps:
      - uses: actions/checkout@v6
      - uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: ./.github/actions
        with:
          version: ${{ env.NGINX131 }}
          latest: true
          latest_major: true
  
  nginx130-build:
    strategy:
      matrix:
        arch:
          - amd64
          - arm64
        include:
          - arch: amd64
            runner: ubuntu-24.04
          - arch: arm64
            runner: ubuntu-24.04-arm
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v6
      - uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: build and push
        env:
          NGINX_VER: ${{ env.NGINX130 }}
          ARCH: ${{ matrix.arch }}
        run: |
          make
          make test
          make push
  nginx130-push:
    runs-on: ubuntu-latest
    needs:
      - nginx130-build
    steps:
      - uses: actions/checkout@v6
      - uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: ./.github/actions
        with:
          version: ${{ env.NGINX130 }}
